/* TIME TOWER: intentionally dependency-free. Rewind restores whole game snapshots,
   rather than trying to invert individual events, which keeps the mechanic reliable. */
(()=>{ 'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),ui=document.querySelector('#ui');
const W=24,H=13,T=48,OY=72,MOVE_TIME=.13,MAX_HISTORY=50,MAX_ENERGY=5;
let level=0, L, game, keys={}, last=0, audio=null, save=loadSave(), screen='menu', endless=false,endlessFloor=0,procedural=false,currentSeed=0;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)); const q=(s)=>document.querySelector(s);
const SKINS=[['shadow','SHADOW RUNNER',0,'The original midnight explorer.','#8aeeff','#0c1020','#57efff'],['street','STREET OPERATIVE',0,'Original white-shirt action operative with a sharp beard and midnight trousers.','#ffba64','#f3f0e8','#ffb35c'],['amber','AMBER PHASE',15,'Warm gold core and amber trail.','#ffd15c','#2b1d08','#ffb648'],['chrono','CHRONO SPECTER',50,'Rare violet time-warp suit.','#d78aff','#21113c','#bc69ff'],['ember','EMBER SCOUT',30,'A fiery red runner from the lower forge.','#ff6b65','#311016','#ff7043'],['mint','MINT VECTOR',40,'A clean green navigation suit.','#6dffd1','#092920','#49e7bd'],['nova','NOVA PILOT',75,'A bright rose core with a stellar trail.','#ff88ce','#32112f','#ff5bb8'],['arctic','ARCTIC WARDEN',110,'Frozen blue armor from the upper tower.','#b8f6ff','#102b45','#70cfff'],['eclipse','ECLIPSE KNIGHT',160,'An ultra-dark suit with solar gold energy.','#ffe17b','#1b1525','#f4c64e'],['prism','PRISM ARCHON',250,'The rarest shifting time costume.','#ffffff','#211052','#9a7dff']];
function skinData(id){return SKINS.find(s=>s[0]===id)||SKINS[0]}
function loadSave(){let defaults={unlocked:1,best:{},highest:1,bestRun:0,coins:0,skins:{shadow:true,street:true,amber:false,chrono:false,ember:false,mint:false,nova:false,arctic:false,eclipse:false,prism:false},equipped:'shadow'};try{let saved=JSON.parse(localStorage.getItem('time-tower-save'))||{};return {...defaults,...saved,skins:{...defaults.skins,...(saved.skins||{})}}}catch(e){return defaults}}
function store(){try{localStorage.setItem('time-tower-save',JSON.stringify(save))}catch(e){}}
function tone(f=.0,d=.08,type='sine',vol=.035){try{audio??=new (window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function buttons(items){return `<div class="menu">${items.map(([a,b,c=''])=>`<button class="button ${c}" data-action="${a}">${b}</button>`).join('')}</div>`}
function menu(){screen='menu';let skin=skinData(save.equipped);ui.innerHTML=`<section class="screen menu-screen"><div class="tower-art"><i></i><b></b><em></em></div><div class="menu-content"><div class="eyebrow">TEMPORAL ASCENT PROTOCOL // ONLINE</div><div class="logo">TIME<br><span>TOWER</span></div><div class="tag">EVERY MISTAKE CAN BE REWRITTEN.</div><div class="menu-brief"><b>REWIND. REPLAN. ESCAPE.</b><br>Climb an endless tower of tactical time puzzles.</div><div class="menu-actions">${buttons([['play','▶  CLIMB THE TOWER','primary'],['endless','ENDLESS RUN ∞'],['daily','DAILY CHALLENGE'],['select','LEVEL SELECT'],['shop',`TIME VAULT • ${save.coins||0} COINS`],['how','HOW TO PLAY'],['settings','SETTINGS']])}</div></div><aside class="operative"><div class="operative-avatar ${skin[0]==='street'?'street-avatar':''}" style="--core:${skin[4]};--suit:${skin[5]};--aura:${skin[6]}"><i></i><b></b><em></em></div><small>CURRENT OPERATIVE</small><strong>${skin[1]}</strong><span>LEVEL ${save.highest} UNLOCKED</span><span>◉ ${save.coins||0} TIME COINS</span></aside><div class="footer">INFINITE SEEDED LEVELS &nbsp; • &nbsp; REWIND THE LAST 5 SECONDS &nbsp; • &nbsp; BUILD ${String(save.highest).padStart(3,'0')}</div></section>`}
function shop(){screen='shop';let cards=SKINS.map(([id,name,cost,desc,core,suit,aura])=>{let owned=!!save.skins?.[id],equipped=save.equipped===id;let action=owned?`equip:${id}`:`buy:${id}`;let label=equipped?'EQUIPPED':owned?'EQUIP':`UNLOCK • ${cost} COINS`;return `<div class="skin-card ${equipped?'selected':''}"><div class="skin-preview ${id==='street'?'street-preview':''}" style="--core:${core};--suit:${suit};--aura:${aura}"><i></i><b></b><em></em></div><h2>${name}</h2><p>${desc}</p><button class="button small" data-action="${action}" ${equipped?'disabled':''}>${label}</button></div>`}).join('');ui.innerHTML=`<section class="screen"><div class="modal vault"><h1>TIME VAULT</h1><p>TIME COINS BANKED: <b style="color:#ffe56f">${save.coins||0}</b> · Select a character to equip it.</p><div class="skin-grid">${cards}</div>${buttons([['menu','BACK','small']])}</div></section>`}
function levelSelect(){screen='select';let max=Math.max(12,save.highest),b='';for(let i=1;i<=max;i++)b+=`<button class="button ${i>save.highest?'locked':'small'}" data-action="level:${i}" ${i>save.highest?'disabled':''}>${String(i).padStart(3,'0')}<br><small>${i<=save.highest?'UNLOCKED':'LOCKED'}</small></button>`;ui.innerHTML=`<section class="screen"><div class="modal"><h1>INFINITE LEVEL SELECT</h1><p>Every numbered level is generated from its permanent seed.</p><div class="levelgrid">${b}</div><br>${buttons([['endless','ENDLESS RUN ∞'],['daily','DAILY CHALLENGE'],['menu','BACK','small']])}</div></section>`}
function how(){screen='how';ui.innerHTML=`<section class="screen"><div class="modal how"><h1>HOW TO PLAY</h1><p><b>MOVE / CLIMB</b> — A/D moves. W/↑ climbs upward and jumps over a one-block gap when facing it. S/↓ descends.</p><p><b>JUMP / SLIDE</b> — From Level 20: press W to jump a pink barrier, and S to slide under an orange bar. These appear only on clear lanes.</p><p><b>TIME COINS</b> — Collect gold time coins on optional routes.</p><p><b>INTERACT</b> — Space activates nearby energy switches. Collect keys by stepping on them.</p><p><b>REWIND</b> — Hold R to scrub backward through the last five seconds. Release R at the moment you want to retry. Rewinding costs limited Time Energy.</p><p><b>GOAL</b> — Reach the cyan exit. Floating blocks create vertical routes; watch patrols and laser rhythms before committing.</p>${buttons([['menu','BACK','small']])}</div></section>`}
function settings(){screen='settings';ui.innerHTML=`<section class="screen"><div class="modal"><h1>SETTINGS</h1><p>Audio is generated procedurally by the browser.<br>Visuals are optimized for a 16:10 display.</p>${buttons([['clear','RESET SAVE','small'],['menu','BACK','small']])}</div></section>`}
function showHUD(){let label=procedural?`${endless?'RUN FLOOR':'LEVEL'} ${String(level).padStart(3,'0')}`:`LEVEL ${String(level+1).padStart(2,'0')}`,runner=game?.map?.flat().join('')||'',extra=runner.includes('J')||runner.includes('V')?' • PINK BARRIER = W JUMP • ORANGE BAR = S SLIDE':'';ui.innerHTML=`<div class="hud"><div class="level">${label} <span style="color:#8aa2c9">// ${L.name} // ${towerTheme().name||'TOWER'} ${procedural?`// SEED ${currentSeed}`:''}</span></div><div class="title">TIME TOWER</div><div class="timer">ESCAPE TIMER <b class="timer-value">${Math.ceil(game?.timeLeft||0)}s</b></div><div class="energy">TIME ENERGY <div class="bar"><div class="fill"></div></div></div><div class="energy" style="right:25px;top:44px">RUN COINS <span class="coin-count">0</span> <small>• BANK ${save.coins||0}</small></div><button class="leave-game" data-action="leave">LEAVE RUN</button><div class="toast"></div><div class="hint"><b style="color:#65efff">A / D = LEFT / RIGHT • W / ↑ = UP • S / ↓ = DOWN</b>${extra} &nbsp; • &nbsp; R = REWIND</div><div class="touch-controls" aria-label="Mobile game controls"><button data-touch="a" aria-label="Move left">◀</button><button data-touch="s" aria-label="Move down or slide">▼</button><button data-touch="w" aria-label="Move up or jump">▲</button><button data-touch="d" aria-label="Move right">▶</button><button class="rewind-touch" data-touch="r" aria-label="Hold to rewind time">⟲</button></div><div class="mobile-tip">TOUCH CONTROLS · HOLD ⟲ TO REWIND</div></div>`}
function toast(t){let x=q('.toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
/* Procedural systems: SeedManager, DifficultyManager, RoomGenerator, ObjectiveGenerator,
   LevelValidator and LevelManager. Templates are deliberately solvable before hazards spawn. */
function hashSeed(n){let x=(n>>>0)+0x9e3779b9;x^=x>>>16;x=Math.imul(x,0x85ebca6b);x^=x>>>13;return (Math.imul(x,0xc2b2ae35)^(x>>>16))>>>0}
function difficulty(n){return 1+Math.log2(n+1)}
function levelTime(n){/* Early floors are short tutorials; complex upper floors earn more planning time. */if(n%10===0)return Math.min(75,38+Math.floor(Math.log2(n+1)*5));return Math.min(65,26+Math.floor(Math.log2(Math.max(1,n)+1)*3)+Math.floor(n/30))}
function validateLevel(spec){let rows=spec.map.map(r=>r.padEnd(W,'#').slice(0,W)),p=find(rows.map(r=>r.split('')),'P'),seen=new Set([p.x+','+p.y]),todo=[p];while(todo.length){let a=todo.shift();if(rows[a.y][a.x]==='X')return true;for(let d of [[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+d[0],y=a.y+d[1],c=rows[y]?.[x]||'#',id=x+','+y;if(c!=='#'&&!seen.has(id)&&c!=='D'&&c!=='G'&&c!=='Q'){seen.add(id);todo.push({x,y})}}}return !!spec.map.join('').match(/[KSGO]/)}
function centerRoute(spec){let rows=spec.map.map(r=>r.padEnd(W,'#').slice(0,W).split('')),used=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(rows[y][x]!=='#')used.push({x,y,c:rows[y][x]});if(!used.length)return 0;let min=Math.min(...used.map(p=>p.y)),max=Math.max(...used.map(p=>p.y)),shift=clamp(Math.round((H-1-(min+max))/2),1-min,H-2-max);if(!shift)return 0;let centered=Array.from({length:H},()=>Array(W).fill('#'));for(let p of used)centered[p.y+shift][p.x]=p.c;spec.map=centered.map(r=>r.join(''));if(spec.enemy)spec.enemy.y+=shift;for(let beam of spec.lasers||[])beam.y+=shift;return shift}
function addDecoyRoutes(spec,n,seed){if(n<15)return;let rows=spec.map.map(r=>r.padEnd(W,'#').slice(0,W).split('')),choices=[];for(let y=1;y<H-2;y++)for(let x=2;x<W-3;x++)if(rows[y][x]==='.')choices.push({x,y});let count=Math.min(1+Math.floor(n/20),5),state=hashSeed(seed^n);while(count&&choices.length){state=hashSeed(state);let i=state%choices.length,p=choices.splice(i,1)[0],dir=(state&1)?-1:1,ny=p.y+dir;if(ny<1||ny>H-2||rows[ny][p.x]!=='#'||rows[ny][p.x+1]!=='#')continue;rows[ny][p.x]='.';rows[ny][p.x+1]='.';let deep=ny+dir;if(deep>0&&deep<H-1&&rows[deep][p.x]==='#'&&n>=35)rows[deep][p.x]='.';if(deep>0&&deep<H-1&&rows[deep][p.x+1]==='#'&&n>=55)rows[deep][p.x+1]='.';count--}spec.map=rows.map(r=>r.join(''))}
function addCoins(spec,n,seed){let rows=spec.map.map(r=>r.padEnd(W,'#').slice(0,W).split('')),spots=[];for(let y=1;y<H-1;y++)for(let x=2;x<W-2;x++)if(rows[y][x]==='.')spots.push({x,y});let state=hashSeed(seed^0x51ed270b),count=Math.min(n<=3?3:2+Math.floor(n/10),8);while(count&&spots.length){state=hashSeed(state);let p=spots.splice(state%spots.length,1)[0];rows[p.y][p.x]='$';count--}spec.map=rows.map(r=>r.join(''))}
function addRunnerObstacles(spec,n,seed){/* Introduced only after the player has learned the tower basics. They are placed
   on straight, two-sided lanes so W/JUMP and S/SLIDE are always fair and readable. */
 if(n<20||n%10===0)return;let rows=spec.map.map(r=>r.padEnd(W,'#').slice(0,W).split('')),spots=[];
 for(let y=1;y<H-1;y++)for(let x=2;x<W-2;x++)if(rows[y][x]==='.'&&rows[y][x-1]!== '#'&&rows[y][x+1]!=='#')spots.push({x,y});
 let state=hashSeed(seed^0x4a554d50),count=n>=55?2:1;
 while(count&&spots.length){state=hashSeed(state);let i=state%spots.length,p=spots.splice(i,1)[0];rows[p.y][p.x]=(state&1)?'J':'V';spots=spots.filter(s=>Math.abs(s.x-p.x)>2||s.y!==p.y);count--}
 spec.map=rows.map(r=>r.join(''))
}
function generateLevel(n,seed=hashSeed(n*7919)){let initialSeed=seed,r=()=>{seed=hashSeed(seed);return seed/4294967296},d=difficulty(n),base=['########################','########################','########################','########################','########################','########################','########################','########################','########################','########################','########################','########################','########################'],hall=[base[0],'#P..................X###',...base.slice(2)],laserX=5+Math.floor(r()*13),crossX=7+Math.floor(r()*10),family=n<=3?0:n<=6?1:n<=9?2:n<=12?3:n<=18?6:n<=24?7:(n-1)%12,tier=Math.floor((n-1)/12)+1,layouts=[
  ['ROUTE','Reach the exit. Read the safe blue path.',hall],
  ['KEY DETOUR','Find the key below, then unlock the exit route.',[base[0],'#P...........D......X###','#.######################','#....K.................#',...base.slice(4)]],
  ['RELAY CLIMB','Climb down to the relay, then open the exit lane.',[base[0],'#P....##################','#####.##################','#....S....G..........X##',...base.slice(4)]],
  ['PRESSURE DESCENT','Descend to charge the plate, then sprint through the timed gate.',[base[0],'#P....##################','#####.##################','#....O......Q........X##',...base.slice(4)]],
  ['KEY CIRCUIT','Take the lower key circuit before opening the sealed gate.',[base[0],'#P......D...........X###','#.######.###############','#.K......###############',...base.slice(4)]],
  ['DOUBLE RELAY','Descend into the chamber: switch first, then use the plate.',[base[0],'#P....##################','#####.##################','#....S...G...O...Q...X##',...base.slice(4)]],
  ['PATROL CROSSING','Cross the lower corridor only after the patrol has moved away.',[base[0],'#P....##################','#####.##################','#....................X##',...base.slice(4)]],
  ['LASER SNAKE','Follow the upper tunnel down into the laser corridor.',[base[0],'#P...........##########','############.##########','#.................X####',...base.slice(4)]],
  ['GUARDED RELAY','Reach the lower relay and choose a safe patrol window.',[base[0],'#P....##################','#####.##################','#....S....G..........X##',...base.slice(4)]],
  ['PULSE PLATE','Take the descent route, then beat the pressure gate and laser.',[base[0],'#P....##################','#####.##################','#....O......Q........X##',...base.slice(4)]],
  ['VAULT','Take the lower key route, return through the gate, then escape.',[base[0],'#P...S...G...D........X#','#.###########.##########','#.K...........##########',...base.slice(4)]],
  ['TIME CORE','Complete a deep circuit: key, relay, sealed gate, plate, exit.',[base[0],'#P....##################','#####.##################','#....S...G..D....O..Q.X#','#.######################','#....K.................#',...base.slice(6)]]
],entry=layouts[family],s={seed:initialSeed,name:`TIER ${tier} // ${entry[0]}`,tip:entry[1],map:entry[2],difficulty:d,pattern:family};
/* A gentle opening: these have distinct room geometry but no mechanic overload. */
if(n===1){s.name='LEVEL 1 // FIRST STEP';s.tip='Follow the bright blue floor to the exit.';}
if(n===2){s.name='LEVEL 2 // CORNER TURN';s.tip='Learn to turn: follow the blue route around the corner.';s.map=[base[0],'#P.....##################','######.#################','#...................X###',...base.slice(4)]}
if(n===3){s.name='LEVEL 3 // FLOATING STEPS';s.tip='Climb the floating steps, jump over the gap, and collect the time coin.';s.map=[base[0],'##C.#$.X################','#C.#####################','#P######################',...base.slice(4)]}
if(n===4){s.name='LEVEL 4 // FIRST KEY';s.tip='Collect the yellow key below, then pass the locked gate.';}
if(n===5){s.name='LEVEL 5 // KEY LOOP';s.tip='Use the lower loop to collect the key, then return to the exit.';s.map=[base[0],'#P......D...........X###','#.######.###############','#.K......###############',...base.slice(4)]}
if(n===6){s.name='LEVEL 6 // KEY DESCENT';s.tip='Take the descent, get the key, and unlock your escape.';s.map=[base[0],'#P....##################','#####.##################','#....K......D........X##',...base.slice(4)]}
if(n===7){s.name='LEVEL 7 // FIRST RELAY';s.tip='Stand next to the switch and press Space to open the gate.';s.map=[base[0],'#P...S....G.........X###',...base.slice(2)]}
if(n===8){s.name='LEVEL 8 // RELAY CLIMB';s.tip='Take the short climb down to activate the relay.';s.map=[base[0],'#P....##################','#####.##################','#....S....G..........X##',...base.slice(4)]}
if(n===9){s.name='LEVEL 9 // RELAY LOOP';s.tip='Go around the upper loop, activate the relay, then return through the gate.';s.map=[base[0],'#P...............#######','################.#######','#X........G....S.#######',...base.slice(4)]}
if(n===10){s.name='LEVEL 10 // FIRST PLATE';s.tip='Stand on the purple plate, then move through the timed gate.';s.map=[base[0],'#P.....O.....Q......X###',...base.slice(2)]}
if(n===11){s.name='LEVEL 11 // PLATE DESCENT';s.tip='Descend to the pressure plate, then run through the timed gate.';s.map=[base[0],'#P....##################','#####.##################','#....O......Q........X##',...base.slice(4)]}
if(n===12){s.name='LEVEL 12 // PLATE LOOP';s.tip='Circle around the top, then return through the plate gate to escape.';s.map=[base[0],'#P...............#######','################.#######','#X....Q....O.....#######',...base.slice(4)]}
let hazardY=[1,3,3,3,1,3,3,3,3,3,1,3][family];
if(family===6||family===8||family===11)s.enemy={x:crossX,y:hazardY,axis:'y',range:3};
if(family===7||family===9||family===10||family===11)s.lasers=[{x:laserX,y:hazardY,axis:'x',range:3}];
/* Each twelve-floor cycle adds decisions, never just speed. The next floor always uses a different family. */
/* Difficulty bands deliberately change the decisions, not just enemy speed. */
if(n>=25&&n<40){let route=n%6,names=['RELAY RUN','DESCENT CIRCUIT','KEY VAULT','RETURN LOOP','PLATE CROSSING','COMPACT CORE'];s.name=`MID TOWER // ${names[route]}`;s.tip='Medium floor: identify the objective path; blue side passages can be dead ends.';s.map=route===0?[base[0],'#P...S....G.........X###',...base.slice(2)]:route===1?[base[0],'#P....##################','#####.##################','#....S....G..........X##',...base.slice(4)]:route===2?[base[0],'#P...S...G...D........X#','#.###########.##########','#.K...........##########',...base.slice(4)]:route===3?[base[0],'#P...............#######','################.#######','#X........G....S.#######',...base.slice(4)]:route===4?[base[0],'#P....##################','#####.##################','#....S...G...O...Q...X##',...base.slice(4)]:[base[0],'#P....##################','#####.##################','#....S...G..D....O..Q.X#','#.######################','#....K.................#',...base.slice(6)];if(n%2)s.enemy={x:crossX,y:route===0||route===3?1:3,axis:'y',range:3};else if(route===0)s.lasers=[{x:laserX,y:-1,axis:'y',range:5}];else s.lasers=[{x:laserX,y:route===3?1:3,axis:'x',range:3}]}
if(n>=40&&n<60){let route=n%2;s.name=`HIGH TOWER // ${route?'CLOCKWORK VAULT':'TIME CIRCUIT'}`;s.tip='High floor: collect the key, power the relay, then time the final escape.';s.map=route?[base[0],'#P...S...G...D........X#','#.###########.##########','#.K...........##########',...base.slice(4)]:[base[0],'#P....##################','#####.##################','#....S...G..D....O..Q.X#','#.######################','#....K.................#',...base.slice(6)];s.enemy={x:crossX,y:route?1:3,axis:'y',range:3};s.lasers=[{x:laserX,y:1,axis:'y',range:5}]}
if(n>=60){s.lasers??=[];s.lasers.push({x:Math.max(4,Math.min(18,laserX+4+(n%3))),y:hazardY,axis:'y',range:2});}
if(n>=61&&family>=8)s.tip+=' Advanced floor: plan the order before moving.';
if(n%10===0){s.name=`BONUS LEVEL ${n} // TIME CACHE`;s.tip='BONUS FLOOR — no hazards. Collect the Time Coins, then reach the exit to continue climbing.';s.map=[base[0],'#P$$$$$$$$$$$$$$$$$$X###',...base.slice(2)];delete s.enemy;delete s.lasers}
/* Horizontal scans sweep left/right; vertical scans enter from above and leave below. */
for(let beam of s.lasers||[])if(beam.axis==='x')beam.x-=beam.range/2;
/* Keep every main route in the visual heart of the tower; later floors branch out from it. */
centerRoute(s);
addDecoyRoutes(s,n,initialSeed);
centerRoute(s);
addRunnerObstacles(s,n,initialSeed);
addCoins(s,n,initialSeed);
return validateLevel(s)?s:generateLevel(n,hashSeed(initialSeed+1))}
function startGenerated(n,run=false,seed){procedural=true;endless=run;endlessFloor=n;level=n;currentSeed=seed??hashSeed(n*7919);start(n,generateLevel(n,currentSeed))}
function startEndless(f=1){startGenerated(f,true,hashSeed((f*7919)^0xdecafbad))}
function start(n=0,custom=null){if(!custom){procedural=false;endless=false}L=custom||TIME_TOWER_LEVELS[clamp(n,0,TIME_TOWER_LEVELS.length-1)];let map=L.map.map(r=>r.padEnd(W,'#').slice(0,W).split('')),p=find(map,'P')||{x:1,y:1},keyPos=find(map,'K'),coinPos=[];for(let y=0;y<map.length;y++)for(let x=0;x<map[y].length;x++)if(map[y][x]==='$')coinPos.push({x,y});let energy=procedural?Math.max(2.5,5-Math.log2(level+1)*.38):MAX_ENERGY,timeLimit=levelTime(procedural?level:level+1);game={map,keyPos,coinPos,coins:0,p:{...p,dir:0,pulse:0,jump:0,slide:0,vertical:0},hasKey:false,switchOn:false,plateTimer:0,enemy:L.enemy?{...L.enemy,baseX:L.enemy.x,baseY:L.enemy.y,phase:0}:null,history:[],energy,maxEnergy:energy,elapsed:0,timeLimit,timeLeft:timeLimit,rewinds:0,mistakes:0,moveCd:0,record:0,rewinding:false,dead:false,complete:false,particles:[],flash:0};map[p.y][p.x]='.';screen='play';showHUD();toast(`${L.tip}  ${timeLimit}s TO ESCAPE  •  SEED ${currentSeed||'—'}`);snapshot();tone(330,.12,'sine');requestAnimationFrame(draw)}
function find(m,ch){for(let y=0;y<m.length;y++){let x=m[y].indexOf(ch);if(x>=0)return{x,y}}}
function tile(x,y){return game?.map[y]?.[x]??'#'}
function plate(){let o=find(game.map,'O');return !!o&&o.x===game.p.x&&o.y===game.p.y}
function openDoor(c){if(c==='D')return game.hasKey;if(c==='G')return game.switchOn||plate()||game.plateTimer>0;if(c==='Q')return plate()||game.plateTimer>0;return c!== '#'}
/* Rewindable world state deliberately excludes run statistics: a player can rewrite
   a mistake in the room, but the end-of-level report must still count it. */
function snapshot(){let g=game;g.history.push({p:{...g.p},hasKey:g.hasKey,keyPresent:!!find(g.map,'K'),coinPresent:(g.coinPos||[]).map(p=>tile(p.x,p.y)==='$'),coins:g.coins,switchOn:g.switchOn,plateTimer:g.plateTimer,enemy:g.enemy&&{...g.enemy},elapsed:g.elapsed,timeLeft:g.timeLeft});if(g.history.length>MAX_HISTORY)g.history.shift()}
function restore(s){game.p={...s.p};game.hasKey=s.hasKey;if(game.keyPos)game.map[game.keyPos.y][game.keyPos.x]=s.keyPresent?'K':'.';(game.coinPos||[]).forEach((p,i)=>game.map[p.y][p.x]=s.coinPresent?.[i]?'$':'.');game.coins=s.coins||0;game.switchOn=s.switchOn;game.plateTimer=s.plateTimer||0;game.enemy=s.enemy&&{...s.enemy};game.elapsed=s.elapsed;game.timeLeft=s.timeLeft??game.timeLeft}
function collectCoin(g,x,y){g.map[y][x]='.';g.coins++;save.coins=(save.coins||0)+1;store();let count=q('.coin-count');if(count)count.textContent=g.coins;tone(880,.12,'sine',.05);toast(`TIME COIN +1  •  BANK ${save.coins}`)}
function tryMove(dx,dy){let g=game;if(g.moveCd||g.dead||g.complete||g.rewinding)return;g.p.dir=Math.atan2(dy,dx);let x=g.p.x+dx,y=g.p.y+dy,c=tile(x,y);if(!openDoor(c)||(c==='C'&&dx)){tone(90,.06,'square');return}if(c==='J'&&!g.p.jump){die();return}if(c==='V'&&!g.p.slide){die();return}g.p.x=x;g.p.y=y;g.p.pulse=.22;g.p.jump=dy?.24:g.p.jump;g.p.vertical=dy;g.moveCd=MOVE_TIME;tone(130,.035,'square',.018);if(c==='C')toast(dy<0?'CLIMBING UP':'CLIMBING DOWN');if(c==='J'||c==='V')g.map[y][x]='.';if(c==='$')collectCoin(g,x,y);if(c==='K'){g.hasKey=true;g.map[y][x]='.';toast('KEY ACQUIRED');tone(660,.16)}if(c==='X')complete();}
function tryJump(){let g=game;if(g.moveCd||g.dead||g.complete||g.rewinding)return false;let dx=Math.round(Math.cos(g.p.dir)),dy=Math.round(Math.sin(g.p.dir));if(!dx||dy)return false;let mid=tile(g.p.x+dx,g.p.y),c=tile(g.p.x+dx*2,g.p.y);if(mid!=='#'||!openDoor(c))return false;g.p.x+=dx*2;g.p.pulse=.36;g.p.jump=.36;g.moveCd=.22;tone(420,.09,'square',.04);toast('GAP JUMP!');if(c==='$')collectCoin(g,g.p.x,g.p.y);if(c==='X')complete();return true}
function interact(){if(screen!=='play'||game.dead)return;let near=[[0,0],[1,0],[-1,0],[0,1],[0,-1]].some(([x,y])=>tile(game.p.x+x,game.p.y+y)==='S');if(near){game.switchOn=!game.switchOn;toast(game.switchOn?'ENERGY RELAY ONLINE':'ENERGY RELAY OFFLINE');tone(game.switchOn?540:180,.16,'sine')}}
function die(reason='TIME INTERRUPTED'){if(game.dead||game.complete)return;game.dead=true;game.mistakes++;game.flash=.4;tone(70,.35,'sawtooth',.08);toast(`${reason} — HOLD R TO RECOVER`);ui.insertAdjacentHTML('beforeend',`<section class="screen fail"><div class="modal"><h1>${reason}</h1><p>Hold <b>R</b> to rewind to a safer moment, or restart this chamber.</p>${buttons([['resume-rewind','REWIND NOW'],['restart','RESTART LEVEL','small']])}</div></section>`)}
function startRewind(){let g=game;if(screen!=='play'||!g.history.length||g.energy<=0||g.complete)return;if(q('.fail'))q('.fail').remove();g.dead=false;g.rewinding=true;g.rewinds++;g.particles=[];tone(720,.24,'sine',.06);toast('REWINDING — RELEASE R TO RESUME')}
function stopRewind(){if(game?.rewinding){game.rewinding=false;tone(390,.1,'sine',.04)}}
function complete(){if(game.complete)return;game.complete=true;let score=Math.max(100,2000+level*35+game.coins*60-Math.round(game.elapsed*12)-game.rewinds*65-game.mistakes*120),best=save.best[level];if(procedural){save.highest=Math.max(save.highest,level+1);if(endless)save.bestRun=Math.max(save.bestRun,level)}else save.unlocked=Math.max(save.unlocked,Math.min(TIME_TOWER_LEVELS.length,level+2));if(!best||score>best.score)save.best[level]={score,time:game.elapsed};store();tone(880,.28,'sine',.06);setTimeout(()=>{screen='complete';let actions=procedural?buttons([['procedural-next',endless?'NEXT RUN FLOOR':'NEXT LEVEL →'],['restart','RETRY','small'],['menu','MAIN MENU','small']]):buttons([['next','NEXT LEVEL'],['restart','RETRY','small'],['select','LEVEL SELECT','small']]);ui.innerHTML=`<section class="screen"><div class="modal"><h1>${procedural?`LEVEL ${level} COMPLETE!`:'LEVEL COMPLETE'}</h1><div class="stats">SEED &nbsp;&nbsp; ${currentSeed}<br>TIME &nbsp;&nbsp; ${game.elapsed.toFixed(1)} s<br>TIME COINS ${game.coins}<br>REWINDS &nbsp; ${game.rewinds}<br>MISTAKES ${game.mistakes}<br><b style="color:#66efff">SCORE &nbsp;&nbsp; ${score}</b></div>${actions}</div></section>`},500)}
function pause(){if(screen!=='play')return;screen='pause';stopRewind();ui.innerHTML=`<section class="screen"><div class="modal"><h1>PAUSED</h1>${buttons([['resume','RESUME'],['restart','RESTART LEVEL'],['leave','LEAVE RUN','small']])}</div></section>`}
function confirmLeave(){if(screen!=='play'&&screen!=='pause')return;screen='confirm-leave';stopRewind();ui.innerHTML=`<section class="screen"><div class="modal"><h1>LEAVE THIS RUN?</h1><p>Your collected Time Coins are already safely banked. Current level progress will be lost.</p>${buttons([['leave-confirm','YES, LEAVE RUN','small'],['leave-cancel','NO, KEEP PLAYING','small']])}</div></section>`}
function resume(){if(screen==='pause'){screen='play';showHUD()}}
function dailySeed(){return hashSeed(Number(new Date().toISOString().slice(0,10).replaceAll('-','')))}
function action(a){tone(250,.04,'square',.02);if(a==='play')startGenerated(Math.max(1,save.highest));else if(a==='endless')startEndless(1);else if(a==='daily'){endless=false;startGenerated(100,dailySeed())}else if(a==='procedural-next')startGenerated(level+1,endless);else if(a==='select')levelSelect();else if(a==='shop')shop();else if(a==='how')how();else if(a==='settings')settings();else if(a==='menu')menu();else if(a==='leave')confirmLeave();else if(a==='leave-confirm')menu();else if(a==='leave-cancel'){screen='play';showHUD()}else if(a==='restart'){if(procedural)startGenerated(level,endless,currentSeed);else start(level)}else if(a==='next')start(level+1);else if(a==='resume')resume();else if(a==='resume-rewind')startRewind();else if(a==='clear'){save={unlocked:1,best:{},highest:1,bestRun:0,coins:0,skins:Object.fromEntries(SKINS.map(s=>[s[0],s[0]==='shadow'])),equipped:'shadow'};store();settings()}else if(a==='quit')menu();else if(a.startsWith('level:'))startGenerated(+a.split(':')[1],false);else if(a.startsWith('equip:')){save.equipped=a.split(':')[1];store();shop()}else if(a.startsWith('buy:')){let id=a.split(':')[1],cost=skinData(id)[2];if((save.coins||0)>=cost){save.coins-=cost;save.skins[id]=true;save.equipped=id;store();shop()}else toast('NOT ENOUGH TIME COINS')}}
ui.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b&&!b.disabled)action(b.dataset.action)});
ui.addEventListener('pointerdown',e=>{let b=e.target.closest('[data-touch]');if(!b)return;e.preventDefault();let key=b.dataset.touch;if(key==='r'){startRewind();return}window.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}))});
ui.addEventListener('pointerup',e=>{let b=e.target.closest('[data-touch="r"]');if(b){e.preventDefault();stopRewind()}});
ui.addEventListener('pointercancel',e=>{if(e.target.closest('[data-touch="r"]'))stopRewind()});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','r','R','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(screen==='play')pause();else if(screen==='pause')resume();return}if(e.key==='r'||e.key==='R'){startRewind();return}if(screen!=='play')return;if(e.key===' '){interact();return}let forward=Math.round(Math.cos(game.p.dir));if(e.key==='w'||e.key==='ArrowUp'){if(forward&&tile(game.p.x+forward,game.p.y)==='J'){game.p.jump=.45;game.p.vertical=-1;tone(470,.08,'square',.04);tryMove(forward,0);return}let above=tile(game.p.x,game.p.y-1);if(openDoor(above)&&above!=='#'){tryMove(0,-1);return}if(tryJump())return;game.p.jump=.45;game.p.vertical=-1;tone(470,.08,'square',.04);toast('JUMP READY');return}if(e.key==='s'||e.key==='ArrowDown'){if(forward&&tile(game.p.x+forward,game.p.y)==='V'){game.p.slide=.45;game.p.vertical=1;tone(190,.08,'square',.04);tryMove(forward,0);return}let below=tile(game.p.x,game.p.y+1);if(openDoor(below)&&below!=='#'){tryMove(0,1);return}game.p.slide=.45;game.p.vertical=1;tone(190,.08,'square',.04);toast('SLIDE READY');return}let dirs={a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};if(dirs[e.key])tryMove(...dirs[e.key])});addEventListener('keyup',e=>{if(e.key==='r'||e.key==='R')stopRewind()});
function update(dt){if(screen!=='play')return;let g=game;g.flash=Math.max(0,g.flash-dt);g.p.pulse=Math.max(0,g.p.pulse-dt);g.p.jump=Math.max(0,(g.p.jump||0)-dt);g.p.slide=Math.max(0,(g.p.slide||0)-dt);if(g.rewinding){let s=g.history.pop();if(s){restore(s);g.energy=clamp(g.energy-.1,0,MAX_ENERGY);for(let i=0;i<3;i++)g.particles.push({x:g.p.x*T+T/2,y:OY+g.p.y*T+T/2,a:1,r:4+Math.random()*8})}else stopRewind();if(g.energy<=0)stopRewind();return}if(g.dead)return;g.elapsed+=dt;g.timeLeft=Math.max(0,g.timeLeft-dt);if(g.timeLeft<=0){die('TIME FRACTURE');return}g.moveCd=Math.max(0,g.moveCd-dt);if(plate())g.plateTimer=3;else g.plateTimer=Math.max(0,g.plateTimer-dt);g.record+=dt;if(g.record>=.1){snapshot();g.record=0}if(g.enemy){let e=g.enemy;e.phase+=dt*.7;let v=Math.sin(e.phase)*e.range/2;e.x=e.baseX+(e.axis==='x'?v:0);e.y=e.baseY+(e.axis==='y'?v:0);let seeing=Math.hypot(e.x-g.p.x,e.y-g.p.y)<3;e.alert=seeing;if(seeing&&!e.beeped){tone(980,.09,'square',.03);e.beeped=true}if(!seeing)e.beeped=false;if(Math.hypot(e.x-g.p.x,e.y-g.p.y)<.64)die()}for(let laser of (L.lasers||[])){let phase=(Math.sin(g.elapsed*2+laser.x)*.5+.5)*laser.range;if(laser.axis==='x'?Math.abs(g.p.y-laser.y)<.35&&Math.abs(g.p.x-(laser.x+phase))<.44:Math.abs(g.p.x-laser.x)<.35&&Math.abs(g.p.y-(laser.y+phase))<.44)die()}let fixed=find(g.map,'L');if(fixed&&g.p.x===fixed.x&&g.p.y===fixed.y)die();g.particles=g.particles.map(p=>({...p,a:p.a-dt*1.8,y:p.y-dt*20})).filter(p=>p.a>0)}
/* Tower themes change every 25 floors, while the rewind ghost visualizes the path being rewritten. */
function towerTheme(){let n=procedural?level:level+1,band=Math.floor((Math.max(1,n)-1)/25)%5;return [{name:'ANCIENT LOWER TOWER',bg:'#050a16',accent:'93,225,255',haze:'#1a3165'},{name:'MECHANICAL TOWER',bg:'#0d0915',accent:'255,155,83',haze:'#572631'},{name:'TIME FACILITY',bg:'#07151c',accent:'83,255,213',haze:'#16534d'},{name:'TEMPORAL LAB',bg:'#180a24',accent:'214,120,255',haze:'#54287b'},{name:'INFINITE DIMENSION',bg:'#130d1b',accent:'255,98,184',haze:'#54245e'}][band]}
function drawRewindGhost(g){if(!g.rewinding||!g.history.length)return;let path=g.history.slice(-16);ctx.save();ctx.globalCompositeOperation='screen';path.forEach((s,i)=>{let x=s.p.x*T+T/2,y=OY+s.p.y*T+T/2;ctx.globalAlpha=.08+i/path.length*.34;ctx.strokeStyle='#a66cff';ctx.shadowBlur=18;ctx.shadowColor='#72f5ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,8+i*.11,0,6.28);ctx.stroke();if(i){let p=path[i-1].p;ctx.beginPath();ctx.moveTo(p.x*T+T/2,OY+p.y*T+T/2);ctx.lineTo(x,y);ctx.stroke()}});ctx.restore()}
/* The level art deliberately separates walkable tiles from tower structure. */
function rect(x,y,w,h,c,glow=0){let palette={'#0a1425':'#1b3457','#0c1729':'#172e4f','#101b31':'#060a14','#263a5e':'#172b4d'};c=palette[c]||c;ctx.fillStyle=c;if(glow){ctx.shadowBlur=glow;ctx.shadowColor=c}ctx.fillRect(x,y,w,h);if((c==='#1b3457'||c==='#172e4f')&&w>=T){ctx.fillStyle='rgba(150,230,255,.12)';ctx.fillRect(x+2,y+2,w-5,3);ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(x+w-5,y+5,3,h-7)}ctx.shadowBlur=0}
function floorTile(x,y,c){rect(x,y,T,T,c);ctx.fillStyle='rgba(126,222,255,.13)';ctx.beginPath();ctx.moveTo(x+2,y+2);ctx.lineTo(x+T-2,y+2);ctx.lineTo(x+T-6,y+7);ctx.lineTo(x+6,y+7);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(0,0,0,.26)';ctx.beginPath();ctx.moveTo(x+T-5,y+7);ctx.lineTo(x+T-2,y+2);ctx.lineTo(x+T-2,y+T-2);ctx.lineTo(x+T-6,y+T-6);ctx.closePath();ctx.fill()}
function drawTowerDepth(t,theme){ctx.save();ctx.globalAlpha=.22;ctx.strokeStyle=`rgba(${theme.accent},.5)`;ctx.lineWidth=1;let vx=576,vy=150;for(let x=-120;x<=1272;x+=96){ctx.beginPath();ctx.moveTo(vx,vy);ctx.lineTo(x,696);ctx.stroke()}for(let y=185;y<696;y+=56){let spread=(y-vy)*1.85;ctx.beginPath();ctx.moveTo(vx-spread,y);ctx.lineTo(vx+spread,y);ctx.stroke()}ctx.globalAlpha=1;ctx.restore()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);let g=game,t=performance.now()/1000;let theme=towerTheme();ctx.fillStyle=theme.bg;ctx.fillRect(0,0,1152,696);let haze=ctx.createRadialGradient(576,300,20,576,300,620);haze.addColorStop(0,theme.haze+'66');haze.addColorStop(1,'transparent');ctx.fillStyle=haze;ctx.fillRect(0,0,1152,696);if(!g)return;for(let i=0;i<28;i++){let x=(i*149+t*(10+i%4)*18)%1152,y=90+(i*71%570);ctx.fillStyle=`rgba(${theme.accent},${.05+.06*Math.sin(t+i)})`;ctx.fillRect(x,y,2,2)}ctx.save();ctx.translate(0,OY);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let c=tile(x,y),px=x*T,py=y*T;rect(px,py,T,T,(x+y)%2?'#0a1425':'#0c1729');ctx.strokeStyle='#1d3150';ctx.globalAlpha=.4;ctx.strokeRect(px+.5,py+.5,T-1,T-1);ctx.globalAlpha=1;if(c==='#'){rect(px,py,T,T,'#101b31');rect(px+3,py+3,T-6,5,'#263a5e');continue}ctx.fillStyle=`rgba(75,215,255,${.035+.025*Math.sin(t*3+x*.7+y)})`;ctx.fillRect(px+3,py+T-5,((t*32+x*9)%T),2);if(c==='X'){rect(px+10,py+6,28,36,'#52eaff',22+8*Math.sin(t*5));rect(px+14,py+10,20,28,'#d3ffff',12)}if(c==='K'){ctx.fillStyle='#ffe76c';ctx.shadowBlur=14;ctx.shadowColor='#ffe76c';ctx.beginPath();ctx.arc(px+22,py+22,9+Math.sin(t*4)*2,0,7);ctx.fill();ctx.shadowBlur=0;rect(px+29,py+20,12,5,'#ffe76c')}if(c==='D'||c==='G'||c==='Q'){let open=openDoor(c),closed=c==='Q'?'#563669':'#602b72';rect(px+4,py+4,40,40,open?'#1c5968':closed,open?16+6*Math.sin(t*5):0);if(!open){ctx.strokeStyle=c==='Q'?'#d0a5ff':'#df7aff';ctx.lineWidth=2+Math.sin(t*4)*.7;ctx.strokeRect(px+8,py+8,32,32)}}if(c==='S'){rect(px+10,py+10,28,28,g.switchOn?'#5effdc':'#384862',g.switchOn?18+5*Math.sin(t*6):0);ctx.fillStyle='#07101d';ctx.fillRect(px+17,py+17,14,14)}if(c==='O'){ctx.strokeStyle=plate()?'#5effdc':'#b987ff';ctx.lineWidth=3+Math.sin(t*5)*.7;ctx.strokeRect(px+7,py+7,34,34)}if(c==='L')laser(px+T/2,py+T/2)}ctx.restore();drawRewindGhost(g);for(let l of L.lasers||[]){let p=(Math.sin(g.elapsed*2+l.x)*.5+.5)*l.range;laser((l.x+(l.axis==='x'?p:0))*T+T/2,OY+(l.y+(l.axis==='y'?p:0))*T+T/2)}if(g.enemy)enemy(g.enemy.x*T+T/2,OY+g.enemy.y*T+T/2,g.enemy);player(g.p.x*T+T/2,OY+g.p.y*T+T/2,g);for(let p of g.particles){ctx.globalAlpha=p.a;ctx.strokeStyle='#8befff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,6.28);ctx.stroke()}ctx.globalAlpha=1;if(g.rewinding){ctx.fillStyle='#9b67ff22';ctx.fillRect(0,0,1152,696);ctx.strokeStyle='#79f4ff';ctx.globalAlpha=.4;ctx.lineWidth=3;ctx.beginPath();ctx.arc(576,348,120+Math.sin(performance.now()/60)*40,0,6.28);ctx.stroke();ctx.globalAlpha=1}if(g.flash){ctx.fillStyle=`rgba(255,75,145,${g.flash})`;ctx.fillRect(0,0,1152,696)}let f=q('.fill');if(f)f.style.width=(g.energy/MAX_ENERGY*100)+'%';let timer=q('.timer');let timerValue=q('.timer-value');if(timerValue)timerValue.textContent=Math.ceil(g.timeLeft)+'s';if(timer)timer.classList.toggle('urgent',g.timeLeft<=10);requestAnimationFrame(draw)}
function drawClimbBlocks(){let t=game?.elapsed||0;ctx.save();ctx.translate(0,OY);for(let cy=0;cy<H;cy++)for(let cx=0;cx<W;cx++)if(tile(cx,cy)==='C'){let bx=cx*T,baseY=cy*T,float=Math.sin(t*2.4+cx*1.8+cy)*5+(cy%2?4:-4),by=baseY+float;ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(bx+24,baseY+42,18,4,0,0,6.28);ctx.fill();ctx.shadowBlur=18;ctx.shadowColor='#46e8ff';rect(bx+5,by+13,38,24,'#16355a',18);ctx.fillStyle='#23517d';ctx.beginPath();ctx.moveTo(bx+5,by+13);ctx.lineTo(bx+13,by+6);ctx.lineTo(bx+47,by+6);ctx.lineTo(bx+43,by+13);ctx.closePath();ctx.fill();ctx.strokeStyle='#7df5ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(bx+8,by+16);ctx.lineTo(bx+40,by+16);ctx.stroke();ctx.fillStyle='#55eaff';ctx.globalAlpha=.75;for(let spark=0;spark<3;spark++)ctx.fillRect(bx+11+spark*10,by+22+Math.sin(t*4+spark)*2,4,3);ctx.globalAlpha=1;ctx.shadowBlur=0}for(let cy=0;cy<H;cy++)for(let cx=0;cx<W;cx++)if(tile(cx,cy)==='$'){let bx=cx*T+24,by=cy*T+24+Math.sin(t*5+cx)*4;ctx.fillStyle='#ffdf57';ctx.shadowBlur=18;ctx.shadowColor='#ffe56f';ctx.beginPath();ctx.arc(bx,by,8,0,6.28);ctx.fill();ctx.fillStyle='#fff6ae';ctx.fillRect(bx-2,by-5,4,10);ctx.shadowBlur=0}ctx.restore();let count=q('.coin-count');if(count)count.textContent=game?.coins||0}
function drawRunnerObstacles(){ctx.save();ctx.translate(0,OY);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let c=tile(x,y),bx=x*T,by=y*T;if(c==='J'){ctx.fillStyle='#fa4f82';ctx.shadowBlur=18;ctx.shadowColor='#ff3d74';ctx.fillRect(bx+4,by+27,40,12);ctx.fillStyle='#ff9dc0';ctx.fillRect(bx+8,by+24,32,4);ctx.shadowBlur=0}if(c==='V'){ctx.strokeStyle='#ff9b48';ctx.shadowBlur=18;ctx.shadowColor='#ff8b36';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(bx+7,by+10);ctx.lineTo(bx+41,by+10);ctx.stroke();ctx.shadowBlur=0}}ctx.restore()}
function player(x,y,g){drawClimbBlocks();drawRunnerObstacles();ctx.save();ctx.translate(x,y);let skin=skinData(save.equipped),core=skin[4],suit=skin[5],aura=skin[6],street=skin[0]==='street';let rise=g.p.jump?Math.sin((g.p.jump/.38)*Math.PI)*15:0,bob=Math.sin(g.elapsed*5)*1.3;ctx.translate(0,bob-rise);let moving=g.moveCd>.02,step=moving?Math.sin(g.elapsed*26)*4:0;if(moving){let dx=Math.cos(g.p.dir),dy=Math.sin(g.p.dir);for(let i=6;i>0;i--){let hue=(g.elapsed*280+i*48)%360,dist=i*5+4;ctx.globalAlpha=.12+i*.075;ctx.fillStyle=`hsl(${hue} 100% 65%)`;ctx.shadowBlur=15;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(-dx*dist,-dy*dist+Math.sin(g.elapsed*16+i)*3,2+i*.72,0,6.28);ctx.fill()}ctx.globalAlpha=1;ctx.shadowBlur=0}if(g.p.slide){ctx.scale(1.25,.58);ctx.translate(0,15)}ctx.shadowBlur=18;ctx.shadowColor=g.rewinding?'#c17cff':aura;ctx.fillStyle='rgba(0,0,0,.52)';ctx.beginPath();ctx.ellipse(0,20,14-rise*.12,4,0,0,6.28);ctx.fill();ctx.shadowBlur=14;ctx.shadowColor='#000';if(street){ctx.fillStyle='#71442c';ctx.beginPath();ctx.arc(0,-10,9,0,6.28);ctx.fill();ctx.fillStyle='#14100f';ctx.beginPath();ctx.arc(0,-15,9,Math.PI,6.28);ctx.fill();ctx.fillRect(-5,-8,10,5)}else{ctx.fillStyle='#080b16';ctx.beginPath();ctx.arc(0,-10,9,0,6.28);ctx.fill()}ctx.fillStyle=suit;ctx.beginPath();ctx.moveTo(-9,1);ctx.quadraticCurveTo(0,-2,9,1);ctx.lineTo(11,16);ctx.lineTo(-11,16);ctx.closePath();ctx.fill();if(street){ctx.strokeStyle='#c8c0b3';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,14);ctx.stroke();ctx.fillStyle='#ffba64';ctx.fillRect(-2,3,4,5)}ctx.strokeStyle=street?'#161923':'#151a30';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-6,14);ctx.lineTo(-7-step*.35,24);ctx.moveTo(6,14);ctx.lineTo(7+step*.35,24);ctx.stroke();ctx.beginPath();ctx.moveTo(-8,3);ctx.lineTo(-13-step*.2,12);ctx.moveTo(8,3);ctx.lineTo(13+step*.2,12);ctx.stroke();ctx.fillStyle=core;ctx.shadowBlur=18;ctx.shadowColor=aura;ctx.beginPath();ctx.arc(0,7,4.5,0,6.28);ctx.fill();ctx.fillStyle=core;ctx.fillRect(-4,-12,8,2);ctx.restore()}
function enemy(x,y,e){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin((game?.elapsed||0)*5)*.08);let alert=game&&Math.hypot(x/T-game.p.x,y/T-OY/T-game.p.y)<3,pulse=1+Math.sin((game?.elapsed||0)*7)*.12;ctx.scale(pulse,pulse);ctx.shadowBlur=alert?26:11;ctx.shadowColor=alert?'#ff426c':'#ff9d5b';ctx.fillStyle='#422846';ctx.beginPath();ctx.moveTo(-14,12);ctx.lineTo(-10,-11);ctx.lineTo(10,-11);ctx.lineTo(14,12);ctx.fill();ctx.fillStyle=alert?'#ff426c':'#ffab66';ctx.fillRect(-8,-4,16,5);ctx.restore()}
function laser(x,y,axis=(L?.lasers?.[0]?.axis||'x')){ctx.save();ctx.translate(x,y);let pulse=1+Math.sin((game?.elapsed||0)*10)*.25;ctx.strokeStyle='#ff4a9e';ctx.shadowBlur=22*pulse;ctx.shadowColor='#ff4a9e';ctx.lineWidth=4*pulse;ctx.beginPath();if(axis==='y'){ctx.moveTo(0,-16);ctx.lineTo(0,16)}else{ctx.moveTo(-16,0);ctx.lineTo(16,0)}ctx.stroke();ctx.restore()}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);requestAnimationFrame(loop)}menu();requestAnimationFrame(loop);requestAnimationFrame(draw);
})();
